frames: []

# when frames are given (few-shot), generate dataloader of size
n-patches: 1000

data-type: pascal

checkpoint-path: None

epochs: 80

# optimizer
lr: 1e-4
momentum: 0.9
alpha: 0.99
eps: 1e-08
weight-decay: 0

# dataset
ds-split: 0.8

# batch
batch-size: 8
batch-norm: True

# dataloader (parallel)
n-workers: 8
cuda: False

# coordconv layers
coordconv: True
coordconv-r: True

# network input size
in-shape: 256

# relative size of patch within original frame
patch-rel-size: 0.3

# gaussian noise
aug-noise: 0.1

# image flipping probability
aug-flip-proba: 0.5
aug-some: 2

# compute loss on square of relative size
loss-size: 0.4

# save training images examples 
save-train-examples: True
n-save-train-examples: 10

# fixed radius masks
fix-radius: 0.05
