epochs: 80
lr: 1e-4
momentum: 0.9
alpha: 0.99
eps: 1e-08
ds-split: 0.8
ds-shuffle: True
weight-decay: 0
batch-size: 8
batch-norm: True
n-workers: 4
cuda: False
coordconv: True
coordconv-r: True
in-shape: 256
patch-rel-size: 0.3
aug-noise: 0.1
aug-flip-proba: 0.5
aug-some: 2
loss-size: 0.4
