frames: []

# when frames are given (few-shot), generate dataloader of size
n-patches: 1000

data-type: pascal

epochs: 80

# optimizer
lr: 1e-4
momentum: 0.9
alpha: 0.99
eps: 1e-08
weight-decay: 0

# dataset
ds-split: 0.8

# batch
batch-size: 4
batch-norm: True

# dataloader
seed: 1
n-workers: 4
cuda: False
fake-len: 200

# coordconv layers
coordconv: True
coordconv-r: True

# network input size
in-shape: 256

# relative size of patch within original frame
patch-rel-size: 0.3

# gaussian noise
aug-noise: 0.1

# image flipping probability
aug-flip-proba: 0.5
aug-some: 2

# compute loss on square of relative size
loss-size: 1.
loss-lambda: 2.

# save training images examples 
save-train-examples: True
n-save-train-examples: 10

# fixed radius masks
fix-radius: 0.05

# for DSAC
init-radius: 0.02
length-snake: 30
gamma: 1
max-px-move: 1
delta-s: 1
n-iter: 200
sigma: 3
alpha-init-weight: 0.
alpha-init-bias: 0.015
beta-init-weight: 0.
beta-init-bias: 0.01
kappa-init-weight: 0.
kappa-init-bias: 10.

